name: Update protobuf-php Repo

on:
  push:
    tags:
      - v[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+-rc[0-9]+

permissions:
  contents: read  #  to fetch code in 'Clone protobuf' (actions/checkout)

jobs:
  update-repo:
    name: Update PHP Repo
    runs-on: ubuntu-latest
    steps:
      - name: Clone protobuf
        uses: actions/checkout@v3
        with:
          path: protobuf
      - name: Get PHP Version
        run: |
          unformatted_version=$( cat protobuf/version.json | jq -r '.main.languages.php' )
          version=${unformatted_version/-rc/RC}
          version_tag=v$version
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV
          echo "VERSION_TAG=$version_tag" >> $GITHUB_ENV
          echo "UNFORMATTED_VERSION=$unformatted_version"
          echo "VERSION=$version"
          echo "VERSION_TAG=$version_tag"
          echo "${{ env.version }}"
          echo "${{ env.action_state }}"
