name: Update protobuf-php Repo

on:
  push:
    tags:
      - v[0-9]+.[0-9]+
    paths:
      - '.github/workflows/**'
    branches:
      - phpAction

jobs:
  update-repo:
    name: Update PHP Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout protobuf-php
        uses: actions/checkout@v3
        with:
          repository: protocolbuffers/protobuf-php
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
      - name: Clone protobuf
        uses: actions/checkout@v3
        with:
          path: protobuf
      - name: Configure Git Bot
        run: |
          git config user.name "Protobuf Team Bot"
          git config user.email "protobuf-team-bot@google.com"
      - name: Get PHP Version
        run: |
          version=$( cat protobuf/version.json | jq '.main.languages.php' )
          echo "VERSION=$version" >> $GITHUB_ENV
      - uses: hmarr/debug-action@v2
      - name: Copy files
        run: |
          rm -rf src
          cp -r protobuf/php/src .
          cp protobuf/php/composer.json.dist composer.json
          rm -rf protobuf
      - name: Push Changes
        run: |
          git add .
          git commit -m "$VERSION sync"
          git push origin test

